# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpSUIEq8Bh9ZHN8_XaJ4CwNAq2_xA-gt

# Welcome to Colab!
"""

def interpolation_search(arr, key):
    low = 0
    high = len(arr) - 1

    while low <= high and key >= arr[low] and key <= arr[high]:

        # If there is only one element
        if low == high:
            if arr[low] == key:
                return low
            return -1

        # Estimate the position
        pos = low + ((key - arr[low]) * (high - low)) // (arr[high] - arr[low])

        # If the element is found
        if arr[pos] == key:
            return pos

        # If key is greater, search right side
        elif arr[pos] < key:
            low = pos + 1

        # If key is smaller, search left side
        else:
            high = pos - 1

    return -1


# Driver Code
arr = [10, 20, 30, 40, 50, 60, 70, 80, 90]
key = int(input("Enter the element to search: "))

result = interpolation_search(arr, key)

if result != -1:
    print("Element found at index:", result)
else:
    print("Element not found")

